branches:
  only:
    - master
gemfile:
  - gemfiles/activerecord_4_2.gemfile
  - gemfiles/activerecord_5_0.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 2.4.4
  - ruby-head
script: bundle exec rspec
